//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webPracA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamResult
    {
        public int ExamPlanId { get; set; }
        public int StudentId { get; set; }
        public Nullable<int> MarkVal { get; set; }
    
        public virtual ExamPlan ExamPlan { get; set; }
        public virtual Mark Mark { get; set; }
        public virtual Student Student { get; set; }
    }
}
