//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webPracA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExamPlan()
        {
            this.ExamResult = new HashSet<ExamResult>();
        }
    
        public int Id { get; set; }
        public int LessonId { get; set; }
        public int GroupId { get; set; }
        public int TeacherId { get; set; }
        public System.DateTime ExamDate { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Lesson Lesson { get; set; }
        public virtual Teacher Teacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamResult> ExamResult { get; set; }
    }
}
